steps:

  # -O0 builds come first for fast feedback.

  - label: (-O0) -A working
    command: |
      NIX_PATH=nixpkgs=nixpkgs nix-build --no-link survey/default.nix \
        --arg disableOptimization true -A working

  - label: (-O0) -A workingStackageExecutables
    command: |
      NIX_PATH=nixpkgs=nixpkgs nix-build --no-link survey/default.nix \
        --arg disableOptimization true -A workingStackageExecutables

  # Normal builds

  - label: -A working
    command: |
      NIX_PATH=nixpkgs=nixpkgs nix-build --no-link survey/default.nix \
        -A working

  - label: -A workingStackageExecutables
    command: |
      NIX_PATH=nixpkgs=nixpkgs nix-build --no-link survey/default.nix \
        -A workingStackageExecutables

  # integer-simple builds

  - label: (integer-simple)
    command: |
      NIX_PATH=nixpkgs=nixpkgs nix-build --no-link survey/default.nix \
        --arg integer-simple true -A working -A workingStackageExecutables

  # Other

  - label: stack2nix-example
    command: |
      cd static-stack2nix-builder-example/ && $(nix-build --no-link -A fullBuildScript)
